### ISSUE TITLE
Include LICENSE for project

### ISSUE THREAD

**Issue by alaxalves** [IgorHalfeld/vue-redtube#2]
It would be cool having a LICENSE for this.

**Comment by IgorHalfeld** [comment]
Wow, I forgot this haha, I'll put on repository, but is under MIT license

**Comment by IgorHalfeld** [comment]
Done! [a5a3e55a9](https://github.com/IgorHalfeld/vue-redtube/commit/a5a3e55a99e80351bf150026321dace726d4bbfe)
